version: '3.3'

services:

  server:
    build:
      context: Server
    links:
      - "database:database"
    environment:
      PORT: 5000
      DB_USER: postgres
      DB_HOST: database
      DB_SCHEME: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      FRONT_URL: "http://localhost:3000"
    ports:
      - "5000:5000"
    depends_on:
      - "database"

  client:
    build:
      context: Client
      args:
        REACT_APP_RECORD_NUMBER_TO_DISPLAY: 10
        REACT_APP_API_ENDPOINT: "http://localhost:5000"

    ports:
    - "3000:80"

  database:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    image: "postgres"
